blog_pages:
    resource: "@BlogBundle/Controller/PagesController.php"
    type:     annotation
    prefix:   /

blog_posts:
    resource: "@BlogBundle/Controller/PostsController.php"
    type:     annotation
    prefix:   /
